version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  cms:
    build:
      context: ./source-code
      dockerfile: ./services/cms-service/Dockerfile
    container_name: cms-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq-service:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
  rms:
    build:
      context: ./source-code
      dockerfile: ./services/rms-service/Dockerfile
    container_name: rms-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq-service:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
  wms:
    build:
      context: ./source-code
      dockerfile: ./services/wms-service/Dockerfile
    container_name: wms-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq-service:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

    
